{{- range .Values.virtualMachines }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app/name: {{ .name }}
  name: {{ .name }}-ssh
  namespace: {{ .namespace }}
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app/name: {{ .name }}
  type: NodePort
{{- end }}
