virtualMachines:
  - name: win11-vm3
    namespace: default
    storage: 60Gi
    hostPath: /opt/user-apps/vm_imgs/vm3/
    storageClassName: local-path
    cpuCores: 3
    memory: 12288Mi
    gpuDeviceName: intel.com/sriov-gpudevice
    secureBoot: false
    usePVC: false
    rdpPort: 3392
    cdiDv: vm3-win11-image
