apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-script-hdmi2
data:
  my_script.sh: |
    #!/bin/sh
    tempFile=`mktemp`
    printf '%s\n' "$4" > $tempFile
    # Add namespace only if qemu namespace doesn't exist (any version)
    if ! grep -q 'xmlns:qemu="[^"]*domain/qemu' $tempFile; then
        sed -i 's|<domain |<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" |g' $tempFile
    fi
    sed -i "s|/devices>|/devices> <qemu:commandline> <qemu:arg value='-display'/> <qemu:arg value='gtk,gl=on,full-screen=on,zoom-to-fit=on,window-close=off,input=off,connectors.0=HDMI-2,hw-cursor=on'/> <qemu:env name='DISPLAY' value=':0'/> <qemu:arg value='-device'/> <qemu:arg value='driver=virtio-vga,max_outputs=1,blob=true,render_sync=false,bus=pcie.0,addr=0x3'/> <qemu:arg value='-usb'/> <qemu:arg value='-device'/> <qemu:arg value='usb-host,hostbus=3,hostport=3.3'/> <qemu:arg value='-usb'/> <qemu:arg value='-device'/> <qemu:arg value='usb-host,hostbus=3,hostport=3.4'/> </qemu:commandline>|" $tempFile
    echo $tempFile > /tmp/t.xml
    cat $tempFile
