# This is a workflow that is triggered to build EMT desktop virtualization (IDV) ISO

name: EMT IDV ISO Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - emt-dv-iso
      - main
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # description to be shown in the UI
        description: 'commit id to build against'
        # Default value if no value is explicitly provided
        default: '3.0.20250718'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build-idv-iso:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Build EMT
      run: |
        #sudo apt-get update && sudo apt-get install genisoimage 
        
        #git init
        #git clone https://github.com/open-edge-platform/edge-microvisor-toolkit.git --branch=3.0
        #ls -lah
        #cd edge-microvisor-toolkit
        #sudo ./toolkit/docs/building/prerequisites-ubuntu.sh
        #sudo ln -vsf /usr/lib/go-1.21/bin/go /usr/bin/go
        #sudo ln -vsf /usr/lib/go-1.21/bin/gofmt /usr/bin/gofmt
        #curl -fsSL https://get.docker.com -o get-docker.sh
        #sudo sh get-docker.sh
        #sudo usermod -aG docker $USER
        
        #git checkout ${{inputs.tag}}
        #cd toolkit
        #wget https://raw.githubusercontent.com/smitesh-sutaria/edge-microvisor-toolkit/refs/heads/3.0/toolkit/imageconfigs/idv.json
        #wget https://raw.githubusercontent.com/smitesh-sutaria/edge-microvisor-toolkit/refs/heads/3.0/toolkit/imageconfigs/idv-m.json
        #mv idv.json ./imageconfigs/
        # mv ./imageconfigs/idv.json ./imageconfigs/full.json
        # mv ./imageconfigs/full.json ./imageconfigs/idv.json
        #sudo make toolchain REBUILD_TOOLS=y VALIDATE_TOOLCHAIN_GPG=n
        #sudo make iso -j8 REBUILD_TOOLS=y REBUILD_PACKAGES=n VALIDATE_TOOLCHAIN_GPG=n CONFIG_FILE=./imageconfigs/idv.json
        # ----------------------------- invoke via script ---------------------------------
        wget https://raw.githubusercontent.com/open-edge-platform/edge-desktop-virtualization/refs/heads/emt-dv-iso/emt-dv-iso/build_idv_iso.sh

        sudo ./build_idv_iso.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: iso
        # A file, directory or wildcard pattern that describes what to upload
        path: idv*.iso
